PREGUNTAS = [
    "¿El docente explica los temas con claridad y coherencia?",
    "¿El docente cumple con la puntualidad en el inicio y desarrollo de las clases?",
    "¿Resuelve las dudas de los estudiantes de manera efectiva y pertinente?",
    "¿Utiliza recursos didácticos adecuados y variados para facilitar el aprendizaje?",
    "¿Promueve y facilita la participación activa de los estudiantes en clase?",
    "¿Muestra respeto y equidad en el trato hacia los estudiantes?",
    "¿Evalúa los conocimientos y habilidades de manera objetiva y justa?",
    "¿Cubre todos los contenidos establecidos en el programa académico de la asignatura?",
    "¿Demuestra interés genuino por el progreso académico de los alumnos?",
    "¿Incentiva a los estudiantes a alcanzar su máximo potencial académico?",
    "¿Domina con solvencia los contenidos temáticos de la asignatura que imparte?",
    "¿Proporciona retroalimentación constructiva y oportuna sobre el desempeño estudiantil?",
    "¿Fomenta el desarrollo del pensamiento crítico y analítico en los alumnos?",
    "¿Muestra disponibilidad para atender consultas y brindar apoyo adicional fuera del horario de clases?",
    "¿Promueve un ambiente de aprendizaje inclusivo y libre de discriminación?",
]
